"""Ports — the abstract boundaries the application layer depends on.

Infrastructure provides concrete adapters that satisfy these Protocols, so the
application/domain never import SQLAlchemy, lxml, rapidfuzz or openpyxl directly
(Dependency Inversion).
"""
from __future__ import annotations

from typing import Protocol

from .entities import Category, LogEntry, MatchItem, PageTerm, ParsedTerm, Term


class VocabRepository(Protocol):
    # categories
    def list_categories(self) -> list[Category]: ...
    def get_category(self, key: str) -> Category | None: ...
    def add_category(self, key: str, label: str, from_keys: list[str]) -> Category: ...
    def unhide_category(self, key: str, label: str) -> Category: ...
    def hide_category(self, key: str) -> None: ...
    def delete_category(self, key: str) -> None: ...
    def categories_using(self, key: str) -> list[str]: ...

    # terms (resolve = union sources for derived categories)
    def resolve_terms(self, cat_key: str) -> list[Term]: ...
    def list_terms(self, cat_key: str) -> list[Term]: ...
    def get_term(self, term_id: str) -> Term | None: ...
    def add_term(self, cat_key: str, canon: str, th: str) -> Term: ...
    def update_term(self, term_id: str, *, canon: str | None, th: str | None, confirmed: bool | None) -> Term: ...
    def delete_term(self, term_id: str) -> None: ...
    def add_alias(self, term_id: str, text: str) -> Term: ...
    def remove_alias(self, term_id: str, text: str) -> Term: ...
    def merge_terms(self, cat_key: str, parsed: list[ParsedTerm]) -> tuple[int, int]: ...


class TrainRepository(Protocol):
    def list(self, category: str | None) -> list[TrainFileLike]: ...
    def add(self, category: str, name: str, rows: int) -> TrainFileLike: ...
    def delete(self, file_id: str) -> bool: ...


class LogRepository(Protocol):
    def write(self, actor: str, action: str, detail: str) -> None: ...
    def list(self, limit: int = 200) -> list[LogEntry]: ...
    def clear(self) -> None: ...


class Crawler(Protocol):
    def fetch_and_extract(self, url: str, bypass_popup: bool) -> tuple[str, list[PageTerm]]:
        """Return (final_url, page_terms). Raise CrawlError on fetch failure."""
        ...


class Matcher(Protocol):
    def match(self, vocab: list[Term], page_terms: list[PageTerm]) -> list[MatchItem]: ...


class ExcelGateway(Protocol):
    def parse(self, filename: str, data: bytes) -> tuple[list[ParsedTerm], int]: ...
    def build_template(self) -> bytes: ...
    def build_export(self, sheet_title: str, terms: list[ParsedTerm]) -> bytes: ...


# TrainFile entity import placed here to avoid a circular import at module top
from .entities import TrainFile as TrainFileLike  # noqa: E402


class CrawlError(Exception):
    """Raised by a Crawler adapter when the page cannot be fetched."""

    def __init__(self, message: str, status: int | None = None):
        super().__init__(message)
        self.status = status
