"""Build-merge engine (kernel-redesign.md §2–§3, "install engine = HYBRID").

The kernel image installs ONLY the kernel's own `requirements.txt` (fastapi/pydantic/cryptography/…).
Every datastore + feature library is **plugin-owned** — declared in that plugin's `backend/requirements.txt`
— because a plugin's code (a tool's `register()` creating the engine, a capability's services) runs
IN the Core process, so its libs must be baked into the image when that plugin is enabled.

This script is the analog of `compose_render` for pip: it MERGES the kernel requirements with the
requirements of the plugins linked under `app/plugins/<id>/` into a single `requirements.lock` that the
Dockerfile installs. Run it AFTER `link-plugins.sh` and BEFORE `docker build`:

    python scripts/render_requirements.py            # → writes Backend/requirements.lock
    python scripts/render_requirements.py --only ai,auth,postgres   # slim: just these plugins + kernel

Pure stdlib (no install needed) so it runs as a host build-prep step. A bare kernel build that never
runs this simply installs `requirements.txt` — Core's plugin-free suite needs nothing more.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
KERNEL_REQS = BACKEND / "requirements.txt"
PLUGINS_DIR = BACKEND / "app" / "plugins"

# package name is everything before the first version/extra/marker delimiter
_NAME_RE = re.compile(r"^([A-Za-z0-9._-]+)")
_PIN_RE = re.compile(r"==\s*([^\s;]+)")


def _normalize(name: str) -> str:
    """PEP 503 normalized distribution name (case-insensitive, _/. → -)."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse(line: str) -> tuple[str, str, str] | None:
    """(normalized_name, pinned_version_or_'', raw_spec) for a requirement line, or None for
    blank/comment lines. `pinned_version` is set only for an exact `==` pin (the case we conflict-check)."""
    spec = line.split("#", 1)[0].strip()
    if not spec:
        return None
    m = _NAME_RE.match(spec)
    if not m:
        return None
    pin = _PIN_RE.search(spec)
    return _normalize(m.group(1)), (pin.group(1) if pin else ""), spec


def _read(path: Path) -> list[tuple[str, str, str]]:
    if not path.is_file():
        return []
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        parsed = _parse(line)
        if parsed:
            out.append(parsed)
    return out


def _plugin_reqs(only: set[str] | None) -> list[tuple[str, str, Path]]:
    """(plugin_id, requirements_path) for each linked plugin that ships a requirements.txt, optionally
    filtered to `only`. Sorted for a deterministic, reproducible lock."""
    found = []
    if not PLUGINS_DIR.is_dir():
        return found
    for child in sorted(PLUGINS_DIR.iterdir()):
        req = child / "requirements.txt"
        if not req.is_file():
            continue
        if only is not None and child.name not in only:
            continue
        found.append((child.name, str(req), req))
    return found


def render(only: set[str] | None) -> tuple[str, dict[str, str]]:
    """Merge kernel + plugin requirements. Returns (lockfile_text, {package: source}). Raises on a
    version conflict (two sources pin the SAME package to DIFFERENT `==` versions) — better to fail the
    build than silently ship one and break the other plugin."""
    chosen: dict[str, str] = {}   # normalized name → raw spec
    pins: dict[str, str] = {}     # normalized name → pinned version
    source: dict[str, str] = {}   # normalized name → where it came from

    def add(items, origin: str) -> None:
        for name, pin, spec in items:
            if name in pins and pin and pins[name] and pin != pins[name]:
                raise SystemExit(
                    f"requirements conflict: '{name}' pinned {pins[name]} ({source[name]}) vs "
                    f"{pin} ({origin}) — reconcile the two plugins' requirements.txt")
            # keep the first spec seen; upgrade to a pinned spec if we only had an unpinned one
            if name not in chosen or (pin and not pins.get(name)):
                chosen[name] = spec
                source[name] = origin
                if pin:
                    pins[name] = pin

    add(_read(KERNEL_REQS), "kernel")
    for pid, _p, path in _plugin_reqs(only):
        add(_read(path), f"plugin:{pid}")

    lines = [
        "# GENERATED by scripts/render_requirements.py — do not edit. Kernel + enabled-plugin requirements",
        "# merged for the image build (kernel-redesign.md §2–§3). Regenerate after linking/changing plugins.",
    ]
    lines += [chosen[name] for name in sorted(chosen)]
    return "\n".join(lines) + "\n", source


def main() -> int:
    ap = argparse.ArgumentParser(description="Merge kernel + plugin requirements into a lockfile.")
    ap.add_argument("--only", help="comma-list of plugin ids to include (default: every linked plugin)")
    ap.add_argument("--output", default=str(BACKEND / "requirements.lock"),
                    help="lockfile path (default: Backend/requirements.lock); '-' = stdout")
    args = ap.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()} if args.only else None

    text, source = render(only)
    if args.output == "-":
        sys.stdout.write(text)
    else:
        Path(args.output).write_text(text, encoding="utf-8")
        plugins = sorted({v.split(":", 1)[1] for v in source.values() if v.startswith("plugin:")})
        n = text.count("\n") - 2  # minus the 2 header comment lines
        print(f"[render_requirements] wrote {args.output}: {n} packages "
              f"(kernel + {len(plugins)} plugins: {', '.join(plugins) or 'none'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
